[package]
name = "xremap"
version = "0.1.0"
edition = "2021"
description = "Dynamic key remapp for X and Wayland"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
evdev = "0.11.3"
getopts = "0.2"
lazy_static = "1.4.0"
log = "0.4.14"
nix = "0.23.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
swayipc = "2.7.2"
x11_rs = { package = "x11", version = "2.19.1", features = ["xlib"] }
zbus = "1.9.2"

[features]
gnome = []
sway = []
x11 = []
